// src/data/companies.js

export const companiesData = [
  {
    id: 1,
    name: "TechCorp Solutions",
    logo: "https://via.placeholder.com/80x80/000000/FFFFFF?text=TC",
    category: "technology",
    rating: 4.5,
    reviewCount: 128,
    description:
      "Leading software development company specializing in enterprise solutions and cloud technologies.",
    founded: "2015",
    employees: "500-1000",
    dateAdded: new Date("2024-01-15"),
  },
  {
    id: 2,
    name: "HealthFirst Medical",
    logo: "https://via.placeholder.com/80x80/2563EB/FFFFFF?text=HF",
    category: "healthcare",
    rating: 4.8,
    reviewCount: 89,
    description:
      "Comprehensive healthcare services with a focus on patient-centered care and medical innovation.",
    founded: "2010",
    employees: "1000+",
    dateAdded: new Date("2024-02-20"),
  },
  {
    id: 3,
    name: "GreenLeaf Restaurants",
    logo: "https://via.placeholder.com/80x80/16A34A/FFFFFF?text=GL",
    category: "food",
    rating: 4.2,
    reviewCount: 256,
    description: "Farm-to-table dining experience with organic ingredients and sustainable practices.",
    founded: "2018",
    employees: "100-500",
    dateAdded: new Date("2024-03-10"),
  },
  {
    id: 4,
    name: "SecureBank Financial",
    logo: "https://via.placeholder.com/80x80/DC2626/FFFFFF?text=SB",
    category: "finance",
    rating: 3.9,
    reviewCount: 167,
    description: "Full-service banking with innovative digital solutions and personalized financial services.",
    founded: "1995",
    employees: "1000+",
    dateAdded: new Date("2024-01-05"),
  },
  {
    id: 5,
    name: "EduLearn Academy",
    logo: "https://via.placeholder.com/80x80/7C3AED/FFFFFF?text=EA",
    category: "education",
    rating: 4.6,
    reviewCount: 94,
    description: "Online learning platform offering courses in technology, business, and creative skills.",
    founded: "2020",
    employees: "50-100",
    dateAdded: new Date("2024-02-28"),
  },
  {
    id: 6,
    name: "StyleHub Retail",
    logo: "https://via.placeholder.com/80x80/EA580C/FFFFFF?text=SH",
    category: "retail",
    rating: 4.1,
    reviewCount: 203,
    description: "Fashion retail chain offering trendy clothing and accessories for all ages.",
    founded: "2012",
    employees: "500-1000",
    dateAdded: new Date("2024-03-15"),
  },
  {
    id: 7,
    name: "AutoDrive Motors",
    logo: "https://via.placeholder.com/80x80/0F172A/FFFFFF?text=AD",
    category: "automotive",
    rating: 4.3,
    reviewCount: 142,
    description: "Innovative car manufacturer focusing on electric vehicles and smart mobility solutions.",
    founded: "2008",
    employees: "1000+",
    dateAdded: "2024-04-01T00:00:00Z",
  },
  {
    id: 8,
    name: "BuildPro Construction",
    logo: "https://via.placeholder.com/80x80/4B5563/FFFFFF?text=BP",
    category: "construction",
    rating: 4.0,
    reviewCount: 76,
    description:
      "Residential and commercial construction services with a commitment to sustainability and quality.",
    founded: "2000",
    employees: "500-1000",
    dateAdded: "2024-03-05T00:00:00Z",
  },
  {
    id: 9,
    name: "NextGen Gaming",
    logo: "https://via.placeholder.com/80x80/9333EA/FFFFFF?text=NG",
    category: "entertainment",
    rating: 4.7,
    reviewCount: 321,
    description: "Game development studio creating immersive experiences for mobile, console, and VR platforms.",
    founded: "2016",
    employees: "200-500",
    dateAdded: "2024-01-28T00:00:00Z",
  },
  {
    id: 10,
    name: "TravelNest Tours",
    logo: "https://via.placeholder.com/80x80/0EA5E9/FFFFFF?text=TN",
    category: "travel",
    rating: 4.4,
    reviewCount: 109,
    description: "Curated travel experiences with personalized itineraries and exclusive packages worldwide.",
    founded: "2013",
    employees: "100-300",
    dateAdded: "2024-02-12T00:00:00Z",
  },
  {
    id: 11,
    name: "FarmFresh Organics",
    logo: "https://via.placeholder.com/80x80/22C55E/FFFFFF?text=FF",
    category: "agriculture",
    rating: 4.5,
    reviewCount: 88,
    description: "Organic farming and delivery service offering fresh produce and dairy to your doorstep.",
    founded: "2011",
    employees: "50-200",
    dateAdded: "2024-03-20T00:00:00Z",
  },
  {
    id: 12,
    name: "PixelPerfect Designs",
    logo: "https://via.placeholder.com/80x80/F43F5E/FFFFFF?text=PD",
    category: "design",
    rating: 4.9,
    reviewCount: 134,
    description: "Creative agency providing UI/UX, branding, and digital marketing services.",
    founded: "2017",
    employees: "50-100",
    dateAdded: "2024-04-10T00:00:00Z",
  },
  {
    id: 13,
    name: "CloudNest Hosting",
    logo: "https://via.placeholder.com/80x80/38BDF8/FFFFFF?text=CN",
    category: "technology",
    rating: 4.2,
    reviewCount: 196,
    description: "Reliable and scalable web hosting solutions with top-tier support.",
    founded: "2012",
    employees: "200-500",
    dateAdded: "2024-02-05T00:00:00Z",
  },
  {
    id: 14,
    name: "UrbanFit Gym",
    logo: "https://via.placeholder.com/80x80/FB923C/FFFFFF?text=UF",
    category: "fitness",
    rating: 4.6,
    reviewCount: 154,
    description: "Modern fitness centers with expert trainers and holistic wellness programs.",
    founded: "2019",
    employees: "100-200",
    dateAdded: "2024-03-25T00:00:00Z",
  },
  {
    id: 15,
    name: "EcoPack Solutions",
    logo: "https://via.placeholder.com/80x80/10B981/FFFFFF?text=EP",
    category: "manufacturing",
    rating: 4.0,
    reviewCount: 63,
    description: "Sustainable packaging products made from biodegradable and recycled materials.",
    founded: "2014",
    employees: "300-600",
    dateAdded: "2024-01-18T00:00:00Z",
  },
  {
    id: 16,
    name: "BrightPath Counseling",
    logo: "https://via.placeholder.com/80x80/F59E0B/FFFFFF?text=BC",
    category: "wellness",
    rating: 4.8,
    reviewCount: 72,
    description:
      "Mental health and counseling services with licensed professionals and flexible online sessions.",
    founded: "2021",
    employees: "20-50",
    dateAdded: "2024-02-22T00:00:00Z",
  },
];

export const categoriesMap = {
  technology: "Technology",
  healthcare: "Healthcare",
  finance: "Finance",
  retail: "Retail",
  education: "Education",
  food: "Food & Beverage",
  automotive: "Automotive",
  "real-estate": "Real Estate",
  construction: "Construction",
  entertainment: "Entertainment",
  travel: "Travel",
  agriculture: "Agriculture",
  design: "Design",
  fitness: "Fitness",
  manufacturing: "Manufacturing",
  wellness: "Wellness",
};

export const companyDetails = {
  name: 'Tech Solutions Inc.',
  logo: 'https://via.placeholder.com/100', // Placeholder image
  industry: 'Software Development',
  location: 'San Francisco, CA',
  description: 'A leading technology company specializing in innovative software solutions for global enterprises, committed to innovation and employee growth.',
  overallRating: 4.5,
  totalReviews: 128,
  website: 'https://www.techsolutions.com',
};

export const reviews = [
  {
    id: 1,
    reviewerName: 'Alice Johnson',
    date: '2023-04-15',
    rating: 5,
    title: 'Excellent Company Culture',
    text: 'I\'ve been working here for 3 years, and the culture is fantastic. Great team and leadership. They truly invest in their employees.',
    helpful: 25,
    isHelpful: false,
  },
  {
    id: 2,
    reviewerName: 'Bob Williams',
    date: '2023-03-20',
    rating: 4,
    title: 'Good Opportunities',
    text: 'Tech Solutions offers good career growth opportunities. Sometimes projects can be challenging but rewarding. The learning curve is steep but worth it.',
    helpful: 18,
    isHelpful: false,
  },
  {
    id: 3,
    reviewerName: 'Charlie Brown',
    date: '2023-05-01',
    rating: 3,
    title: 'Average Experience',
    text: 'It\'s an average workplace. Some processes could be improved, but overall decent. The commute can be a bit challenging sometimes.',
    helpful: 5,
    isHelpful: false,
  },
  {
    id: 4,
    reviewerName: 'Diana Prince',
    date: '2023-02-10',
    rating: 5,
    title: 'Highly Recommend!',
    text: 'An amazing place to work! Supportive colleagues and cutting-edge projects. Couldn\'t ask for more. Every day brings a new exciting challenge.',
    helpful: 40,
    isHelpful: false,
  },
  {
    id: 5,
    reviewerName: 'Eve Adams',
    date: '2023-01-05',
    rating: 2,
    title: 'Needs Improvement',
    text: 'Communication could be better. Some management issues need addressing. There\'s a disconnect between different departments.',
    helpful: 10,
    isHelpful: false,
  },
  {
    id: 6,
    reviewerName: 'Frank White',
    date: '2022-12-01',
    rating: 4,
    title: 'Positive Environment',
    text: 'Generally a good place to work. Friendly atmosphere and interesting projects. The team collaboration is a definite strong point.',
    helpful: 15,
    isHelpful: false,
  },
  {
    id: 7,
    reviewerName: 'Grace Lee',
    date: '2023-01-20',
    rating: 5,
    title: 'Fantastic Benefits',
    text: 'The benefits package is top-notch, and they truly care about employee well-being. From health to wellness, everything is covered.',
    helpful: 30,
    isHelpful: false,
  },
  {
    id: 8,
    reviewerName: 'Henry Green',
    date: '2023-03-01',
    rating: 3,
    title: 'Work-Life Balance Varies',
    text: 'Depending on the project, work-life balance can be good or challenging. Some periods require more dedication than others.',
    helpful: 7,
    isHelpful: false,
  },
  {
    id: 9,
    reviewerName: 'Ivy King',
    date: '2023-04-01',
    rating: 4,
    title: 'Innovative Projects',
    text: 'I enjoy working on the innovative projects here. Always something new to learn and apply, pushing the boundaries of technology.',
    helpful: 22,
    isHelpful: false,
  },
  {
    id: 10,
    reviewerName: 'Jack Blue',
    date: '2023-02-25',
    rating: 1,
    title: 'Poor Management',
    text: 'Management needs significant improvement. High turnover in some departments is a clear sign of underlying issues.',
    helpful: 12,
    isHelpful: false,
  },
];